import Head from 'next/head'
import styles from  '../styles/Home.module.css'
import Character from './character'
import {useEffect,useState} from 'react'
export default function Home() {
  const [characters,setCharacters] = useState([]);
  const [loading,setLoading] = useState(true);

  useEffect(()=>{
    async function fetchdata(){
      const response = await fetch('https://rickandmortyapi.com/api/character/');
      const data = await response.json();
      setCharacters(data.results);  
      
      setLoading(false);
    }
    
    fetchdata();
  },[characters.length]);
  return (
    <div >
      <Head>
        <title>just learning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../favicon.ico" />
      </Head>
      <div className={styles.heading}>Rick and Morty</div>
      <h1>Characters</h1>
      <div className={styles.allcharacters}>
      {loading ? <h1>Loading...</h1> : characters.map(character=>{
        return <Character key={character.id} name={character.name} image={character.image} origin={character.origin.name} id={character.id}/>
      })
     }
     </div>
    </div>
  )
}
