import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import MeetupLists from "../components/meetups/meetuplist";
import MainNavigation from "../components/layouts/mainnavigation";
export default function Home() {
  const DUMMY_DATA = [
    {
      id: 1,
      title: "Meetup 1",
      image: "https://picsum.photos/200/300",
      address: "123 Main St, New York, NY 10001",
      discription: "This is the first meetup",
    },
    {
      id: 2,
      title: "Meetup 2",
      image: "https://picsum.photos/200/300",
      address: "123 Main St, New York, NY 10001",
      discription: "This is the second meetup",
    },
    {
      id: 3,
      title: "Meetup 3",
      image: "https://picsum.photos/200/300",
      address: "123 Main St, New York, NY 10001",
      discription: "This is the third meetup",
    },
  ];
  return (
    <div>
      <Head>
        <title>learning next js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../favicon.ico" />
      </Head>
      <MainNavigation />
      <MeetupLists meetups={DUMMY_DATA} />
    </div>
  );
}
