import Head from 'next/head'
import styles from  '../styles/Home.module.css'
import About from './about/about'
export default function Home() {
  
  return (
    <div >
      <Head>
        <title>just learning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../favicon.ico" />
      </Head>
      <div className={styles.heading}>MY PORTFOLIO</div>
      <About/>
    </div>
  )
}
